# inherited from
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  RunRailsCops: true
  DisplayCopNames: true

Style/BlockDelimiters:
  EnforcedStyle: semantic
  ProceduralMethods:
    - benchmark
    - bm
    - bmbm
    - create
    - each_with_object
    - measure
    - new
    - realtime
    - tap
    - with_object
    - map
  FunctionalMethods:
    - let
    - let!
    - subject
    - watch
    - before
    - sequence
    - expose
  IgnoredMethods:
    - lambda
    - proc
    - it
    - any?
    - password_confirmation
    - level
    - kind
    - each

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/LambdaCall:
  EnforcedStyle: braces
